### ISSUE TITLE
split_folders.ratio() to have "oversample" parameter.

### ISSUE THREAD

**Issue by gohjunyi** [jfilter/split-folders#12]
I wanted to split the images into train, val and test.
`split_folders.ratio('data/images', output="data/images_new", seed=1337, ratio=(.8, .1, .1))
`
~~1) I realized that there are many copies for the classes with small samples. Would like to find out whether using the ratio method will automatically balance the data set?~~

2) If yes, would it also be possible to add a parameter "oversample" for ratio method?

**Comment by gjunyi90** [comment]
Part 1 of the issue is **invalid** as I have ran the code again and it generated without any performing oversampling.

**Comment by jfilter** [comment]
But how would you choose the number of items for train / val / test? I guess it would make sense to go over all classes and choose the ratio from the class with the most items. But this would get tricky / complicated. I am not sure if this is really helpful.

**Comment by iam8github** [comment]
Hey @jfilter ,

First of all, let me admire your efforts for making our lives so easy by developing this very handy tool. However, there is problem for imbalanced number of files in folders. In my case I want to keep exactly 200 files for training and rest for the test/validation regardless of how many files left for test/validation. If I do so following your code guidelines;

To only split into training and validation set, use a single number to fixed, i.e., 10.
I got the following assertion error. Could you please help me to resolve this issue.

TypeError Traceback (most recent call last)
in ()
7
8 #no_files
----> 9 sp.fixed(data_dir, output=output_dir, seed=13, fixed=200, oversample=False, group_prefix=None) # default values

/usr/local/lib/python3.6/dist-packages/splitfolders/split.py in fixed(input, output, seed, fixed, oversample, group_prefix)
96 fixed = fixed
97
---> 98 assert len(fixed) in (1, 2)
99
100 if tqdm_is_installed:

TypeError: object of type 'int' has no len()

**Comment by jfilter** [comment]
If anybody wants to work on this, please open a new issue.
