### ISSUE TITLE
warn user if folders are not in the right format

### ISSUE THREAD

**Issue by rahulsingh50** [jfilter/split-folders#13]
(cv2020) hduser@slave1:~/computer_vision_2020/staff_detecion_using_icard/data$ split_folders images --ratio .8 .2
Copying files: 0 files [00:00, ? files/s]
when i done it say copying 0 files.

**Comment by jfilter** [comment]
I'm sorry but I can't help you. Generally, this package works.

**Comment by artmatsak** [comment]
For anyone else facing this issue, make sure that your image folder contains subfolders corresponding to the image classes. See the header comment [here](https://github.com/jfilter/split-folders/blob/master/splitfolders/split.py).

**Comment by jfilter** [comment]
Now I get the problem. The package should report a proper error message if the folders are not the right format.

**Comment by r02b** [comment]
Note that currently, if one has the 'tqdm' package installed, it would actually output a helpful hint:
`Copying files: 0 files [00:00, ? files/s]`
