### ISSUE TITLE
Ratio not found

### ISSUE THREAD

**Issue by mavaylon1** [jfilter/split-folders#18]
import splitfolders

splitfolders.ratio("/Users/mavaylon/Research/Research_Gambier/Data_P/BP", output="/Users/mavaylon/Research/Research_Gambier/Data_P/output", seed=1337, ratio=(.7, .3), group_prefix=None) # default values

This just returns ratio is not an attribute.

**Comment by jfilter** [comment]
What's the output of the following?

```python
print(splitfolders.__version__)
```

**Comment by mavaylon1** [comment]
0.4.2

**Comment by jfilter** [comment]
What Python version are you using? What's your OS?

**Comment by mavaylon1** [comment]
OS Catalina 10.15.6
Python 3.7.6

**Comment by jfilter** [comment]
Do you have file named `splitfolders.py` in your folder? Does it work with by using this package like this? 

```python
import split_folders
```

**Comment by jfilter** [comment]
So I assume @mavaylon1 named her or his script `splitfolders.py` and close this for now. If not, please comment again and we will find a solution.
