### ISSUE TITLE
Does not work with relative paths

### ISSUE THREAD

**Issue by risto-trajanov** [jfilter/split-folders#21]
import splitfolders
	splitfolders.ratio("./input_folder", output="./output", seed=1337, ratio=(.8, .1, .1), group_prefix=None)

Error:

    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'input_folder'

My folder
 - root
	 - input_folder
		 - Covid-19
		 - No_findings
	 - output
	 - split_folder_script.ipynb

**Comment by LindaK2013** [comment]
also my issue, I do not know how to call the output file(s) to use them

**Comment by jfilter** [comment]
Relative paths work, not sure why it wasn't working in your case. If anybody can create a reproducible environment (Dockerfile) where it's not working, I will take a look at it.
