### ISSUE TITLE
Split folders to work without a "class" hierarchy

### ISSUE THREAD

**Issue by r02b** [jfilter/split-folders#22]
Since splitting data into (test, train, validation) sets is relevant to all data types, not just ones that are related different classes, having the option to use split-folder on a general folder, i.e. one that contains actual data and does not comply with the subdir ('class1', 'class2',...) hierarchy, would make this package relevant to a much larger crowd.

**Comment by jfilter** [comment]
If you want to split files in single folder, do the following:

1. create an input folder, e.g., `input`
2. create another folder, e.g., `dummy` within `input`.
3. now split the folder like this: `splitfolders --ratio .8 .1 .1 -- input`

If you have an array of data, take a look in the following from scikit-learn: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

**Comment by PatrickKudo** [comment]
I don't think creating dummy folders is an effective solution.
