### ISSUE TITLE
split_folders not working

### ISSUE THREAD

**Issue by sandeeppandey456** [jfilter/split-folders#23]
I have a directory containing two classes - 0 and 1 , consisting of subfolders with wave files. The structure is - 
`main folder
`--class 1
`     ---- speaker1
`              ----wavefile1
               ---wavefile2
               ---wavefile3
`
      -----speaker2
         ........
`
`--class 2
`     ---- speaker1
      -----speaker2
         ........
`
Splitfile is not working when using the syntax given in the example

**Comment by jacobmcasey** [comment]
I just ran on some wav files and it is working just fine. Could you share your "syntax" that isn't working?

**Comment by Yukti-09** [comment]
I am facing the same issue. I have hereby attached a code snippet.

`import splitfolders ` <br>
`split_folders.ratio('path', output="output", seed=1337, ratio=(.8, 0.1,0.1))`

The error is:
NameError                                 Traceback (most recent call last)
<ipython-input-6-51585f2960ac> in <module>
      1 import splitfolders
----> 2 split_folders.ratio('path', output="output", seed=1337, ratio=(.8, 0.1,0.1))

NameError: name 'split_folders' is not defined

**Comment by jfilter** [comment]
> `import splitfolders`
>  `split_folders.ratio('path', output="output", seed=1337, ratio=(.8, 0.1,0.1))`

You have to use `splitfolders.ratio(...)` if you import the package like this
