### ISSUE TITLE
Specify the exact number of items for training/validation/test sets

### ISSUE THREAD

**Issue by JulianJB** [jfilter/split-folders#24]
I understand that by version `0.4.3` it is possible to specify the exact number of items for the validation and test sets by using the flag **--fixed**, however, as the documentation states:

The remaining items constitute the training set. e.g. for train/val/test `100 100` or for train/val `100`.

Meaning that you can currently specify the number of items for the validation and test sets but not for the training set, so in a scenario where a given range of images (i.e. a subset from a larger dataset) it would be useful to be able to specify a fixed number of items for each of the sets.

More than an issue, a feature request. Thanks.

**Comment by jfilter** [comment]
Thanks for proposing. I agree that it makes sense to limit the number of training samples. Currently, oversampling together with three values for fixed is not implemented. If anybody wants to take a look at it, please open a new issue.
