### ISSUE TITLE
Suggestion: Make default seed random and allow for Cross Validation folders

### ISSUE THREAD

**Issue by AlejandroBaron** [jfilter/split-folders#26]
Hello!

According to https://pypi.org/project/split-folders/ , the default seed is 1337, so I'm assuming this make always the train-val-test split always the same?

And furthermore, a good idea would be to include an option to divide the train folder into X-folds for cross validation!

**Comment by jfilter** [comment]
Hey, you can configure the seed. Check out the usage guide: https://github.com/jfilter/split-folders#module
