### ISSUE TITLE
splitfolders is not copying files but execute without error

### ISSUE THREAD

**Issue by krishnainc** [jfilter/split-folders#30]
This is my code snippet

`import splitfolders
import os

os.makedirs('output')
images = 'img'
splitfolders.ratio(images, output= 'output', seed=42, ratio = (.7,.2,.1))`

**Comment by waterflyer** [comment]
ok, I just found the right way to use it, you need to create a subfolder under your "img" folder, such as "data", then after you executed the program, it will generate 3 folders that are test, train and val under your output folder, and inside those 3 folders, it will create a subfolder named "data" as well, and finally it will contain the images after the splitting as your specified ratio.

**Comment by jfilter** [comment]
This is a duplicate of #13.
