### ISSUE TITLE
AttributeError: module 'split_folders' has no attribute 'ratio'

### ISSUE THREAD

**Issue by chontipan** [jfilter/split-folders#6]
Hi, i run "split_folders.ratio('img_data/', output="output", seed=1500, ratio=(.8, .1, .1))" and get AttributeError: module 'split_folders' has no attribute 'ratio'

My dataset have 15 sub-folders containing 100 images for each

**Comment by chontipan** [comment]
Sorry, I just know the cause. I set my filename as split_folders. py

**Comment by mavaylon1** [comment]
I'm having the same issue. What is the fix?

**Comment by chontipan** [comment]
As I remember, it is about the filename. You can try to change your file name to others.
