### ISSUE TITLE
Split by Ratio

### ISSUE THREAD

**Issue by GregBueno** [jfilter/split-folders#8]
Hi dude, 
Verify the ratio by .7 .2 .1, the sum ratio result: 0.9999999999999999
See the print.
![image](https://user-images.githubusercontent.com/48804211/60724979-48b9b780-9f0e-11e9-9c19-bf1284dedf45.png)

**Comment by jfilter** [comment]
Thanks for flagging this. Fixed in https://github.com/jfilter/split-folders/commit/e9f7a4fdcea8861843aace39c2fca36fe89bf52b.
