### ISSUE TITLE
Show progress bar 

### ISSUE THREAD

**Issue by MariusMez** [jfilter/split-folders#9]
Hi, nice and usefull little project.

May I suggest adding tool like TQDM https://tqdm.github.io to show advancement of the copy in case of big datasets which take time to process.

It's easy to add I think and could do a PR if you want to, but as I don't know the philosophy of your project (are external dependancy allowed ?)
I'll wait for your return.

**Comment by jfilter** [comment]
Hey Marius,
let's do it like this: If tqdm is installed, the progress bar is shown. Otherwise there is no progress bar. I am happy to accept your PR. ;)
